Update misajour to take a source branch

diff --git a/misajour b/misajour
--- a/misajour
+++ b/misajour
@@ -1,14 +1,21 @@
-#!/usr/local/bin/bash
+#!/bin/bash
 
 usage () {
-  echo 'usage: misajour [-h]'
+  echo 'usage: misajour [-h] branch'
   echo 'Run misajour from a git repo to automatically update'
-  echo 'and rebase the master branch onto the current branch'
+  echo 'and rebase a source branch onto the current branch'
 }
 
 if [ "$1" == -h ] ; then
   usage
   exit 0
+fi
+
+if [ "$1" ] ; then
+  source=$1
+else
+  echo 'Must provide a source branch'
+  exit 1
 fi
 
 (git rev-parse --git-dir >/dev/null 2>&1)
@@ -19,6 +26,13 @@ if [ $? -ne 0 ] ; then
   exit 1
 fi
 
+git rev-parse --verify $source >/dev/null 2>&1
+
+if [ $? -ne 0 ] ; then
+  echo "Could not find branch $source"
+  exit 1
+fi
+
 function current_branch()
 {
   echo $(git rev-parse --abbrev-ref HEAD)
@@ -26,10 +40,10 @@ function current_branch()
 
 target=$(current_branch)
 
-if [ "$target" == 'master' ]
+if [ "$target" == "$source" ]
 then
-  echo "Cannot `basename $0` the master branch"
-  echo "Please checkout a different one"
+  echo "Cannot `basename $0` the same branch"
+  echo "Please use a different source"
   exit 1
 fi
 
@@ -42,20 +56,20 @@ then
   exit 1
 fi
 
-echo "Preparing to rebase master onto" $target
-git checkout master
+echo "Preparing to rebase $source onto $target"
+git checkout $source
 
-echo "Updating master..."
+echo "Updating $source..."
 git pull -q --rebase
 git checkout $target
 
 if [ $target == $(current_branch) ]
 then
-  echo "Rebasing master onto" $target"..."
-  git rebase master
+  echo "Rebasing $source onto $target..."
+  git rebase $source
 else
-  echo "Aborting: unable to switch back to" $target
-  echo "There was a problem updating master"
+  echo "Aborting: unable to switch back to $target"
+  echo "There was a problem updating $source"
 fi
 
 exit $?
